import { execFile } from "node:child_process";
import { copyFile, mkdir, mkdtemp, readFile, rename, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";
import { parse as parseToml } from "smol-toml";
import { afterEach, beforeEach, describe, expect, test } from "vitest";
import { generateAgents, renderCodexAgent, renderReviewer } from "../scripts/generate-agents.ts";

const exec = promisify(execFile);
const root = resolve(import.meta.dirname, "..");
const template = "{{introduction}}\n\nShared boundary.\n\n{{review}}\n\n{{focus}}\n\n{{report}}\n";
const role = "---\nname: sample-reviewer\ndescription: Sample role\n---\n\n# Sample\n\nIntroduction.\n\n## Focus\n\nSpecific focus.\n";
const reviewing = "# Reviewing\n\n## Selection\n\nParent-only selection.\n\n## Review\n\nShared review.\n\n## Report\n\nShared report.\n\n## Other\n\nUnrelated section.\n";

describe("reviewer composition", () => {
  test("preserves frontmatter and specialist content while including only the selected shared sections", () => {
    const result = renderReviewer(template, role, reviewing);
    expect(result).toMatch(/^---\nname: sample-reviewer\ndescription: Sample role\n---\n/);
    expect(result).toContain("<!-- Generated by scripts/generate-agents.ts.");
    expect(result).toContain("# Sample\n\nIntroduction.");
    expect(result).toContain("Shared boundary.\n\n## Review\n\nShared review.\n\n## Focus\n\nSpecific focus.\n\n## Report\n\nShared report.\n");
    expect(result).not.toContain("Parent-only selection.");
    expect(result).not.toContain("Unrelated section.");
    expect(result).not.toContain("{{");
    expect(renderReviewer(template, role, reviewing)).toBe(result);
    const crlf = (text: string) => text.replaceAll("\n", "\r\n");
    expect(renderReviewer(crlf(template), crlf(role), crlf(reviewing))).toBe(result);
  });

  test.each([
    template.replace("{{review}}", ""),
    template.replace("{{review}}", "{{unknown}}"),
    template + "{{report}}",
  ])("rejects missing, unknown, or duplicate composition slots", (invalid) => {
    expect(() => renderReviewer(invalid, role, reviewing)).toThrow("slot");
  });

  test("reports missing source sections rather than silently omitting them", () => {
    expect(() => renderReviewer(template, role.replace("## Focus", "## Other"), reviewing)).toThrow("## Focus");
    expect(() => renderReviewer(template, role, reviewing.replace("## Report", "## Other report"))).toThrow("## Report");
  });

  test("committed reviewers match their authoritative sources", async () => {
    expect(await generateAgents(root, true)).toEqual([]);
  });
});

describe("Codex rendering", () => {
  test("serializes metadata and the complete body without carrying build notices into instructions", () => {
    const markdown = renderReviewer(template, role, reviewing);
    const rendered = renderCodexAgent(markdown);
    expect(rendered.name).toBe("sample-reviewer");
    expect(parseToml(rendered.content)).toEqual({
      name: "sample-reviewer",
      description: "Sample role",
      developer_instructions: markdown.split("---\n").slice(2).join("---\n")
        .replace(/<!-- Generated by scripts\/generate-agents\.ts\.[^\n]* -->\n/, "").trim(),
    });
    expect(rendered.content).toMatch(/^# Generated by scripts\/generate-agents\.ts\./);
    expect(renderCodexAgent(markdown.replaceAll("\n", "\r\n"))).toEqual(rendered);
  });

  test("round-trips YAML scalar styles and TOML-sensitive instruction text", () => {
    const instructions = '# Example\n\nQuotes: """ and \'\'\'; path: C:\\tools\\new; tab:\t; Unicode: Müller.\n';
    const rendered = renderCodexAgent(`---\nname: sample\ndescription: >-\n  Multiple lines,\n  one description.\n---\n\n${instructions}`);
    expect(parseToml(rendered.content)).toEqual({
      name: "sample",
      description: "Multiple lines, one description.",
      developer_instructions: instructions.trim(),
    });
  });

  test.each([
    ["No frontmatter.", "frontmatter"],
    [role.replace("sample-reviewer", "../escape"), "name"],
    [role.replace("description: Sample role", "description: 42"), "description"],
    ["---\nname: sample\ndescription: Sample\n---\n", "instructions"],
  ])("rejects invalid canonical roles before serialization", (markdown, error) => {
    expect(() => renderCodexAgent(markdown)).toThrow(error);
  });
});

describe("generation and drift checking", () => {
  let directory: string;
  const handwritten = "---\nname: handwritten\ndescription: Handwritten role\n---\n\nHandwritten instructions.\n";
  const initialOutputs = [
    "agents/first.md", "agents/second.md",
    "codex/agents/handwritten.toml", "codex/agents/sample-reviewer.toml", "codex/agents/second-reviewer.toml",
  ];

  beforeEach(async () => {
    directory = await mkdtemp(join(tmpdir(), "agentic-skills-generation-"));
    for (const path of ["templates/reviewers/roles", "skills/agentic-reviewing", "agents", "scripts"]) {
      await mkdir(join(directory, path), { recursive: true });
    }
    await writeFile(join(directory, "templates/reviewers/template.md"), template);
    await writeFile(join(directory, "templates/reviewers/roles/first.md"), role);
    await writeFile(join(directory, "templates/reviewers/roles/second.md"), role.replace("sample-reviewer", "second-reviewer"));
    await writeFile(join(directory, "skills/agentic-reviewing/SKILL.md"), reviewing);
    await writeFile(join(directory, "agents/handwritten.md"), handwritten);
  });

  afterEach(async () => {
    await rm(directory, { recursive: true, force: true });
  });

  test("check detects missing output directories without creating them", async () => {
    expect(await generateAgents(directory, true)).toEqual(initialOutputs);
    await expect(readFile(join(directory, "agents/first.md"))).rejects.toMatchObject({ code: "ENOENT" });
    await expect(readFile(join(directory, "codex/agents"))).rejects.toMatchObject({ code: "ENOENT" });
  });

  test("generates both formats and propagates shared source changes to every reviewer", async () => {
    expect(await generateAgents(directory)).toEqual(initialOutputs);
    expect(await generateAgents(directory)).toEqual([]);
    expect(await generateAgents(directory, true)).toEqual([]);

    await writeFile(join(directory, "skills/agentic-reviewing/SKILL.md"), reviewing.replace("Shared review.", "Updated method."));
    expect(await generateAgents(directory)).toEqual([
      "agents/first.md", "agents/second.md", "codex/agents/sample-reviewer.toml", "codex/agents/second-reviewer.toml",
    ]);
    for (const [file, name] of [["first", "sample-reviewer"], ["second", "second-reviewer"]]) {
      const markdown = await readFile(join(directory, `agents/${file}.md`), "utf8");
      const codex = parseToml(await readFile(join(directory, `codex/agents/${name}.toml`), "utf8"));
      for (const content of [markdown, codex.developer_instructions]) {
        expect(content).toContain("Updated method.");
        expect(content).toContain("Specific focus.");
        expect(content).toContain("Shared report.");
      }
    }
    expect(await readFile(join(directory, "agents/handwritten.md"), "utf8")).toBe(handwritten);
  });

  test("check detects drift without mutation; generation reconciles only owned outputs", async () => {
    await generateAgents(directory);
    const previous = await readFile(join(directory, "agents/first.md"), "utf8");
    await rename(join(directory, "templates/reviewers/roles/first.md"), join(directory, "templates/reviewers/roles/renamed.md"));
    // Removing a current reviewer's notice does not turn it into a handwritten source.
    await writeFile(join(directory, "agents/second.md"), "Edited output.\n");
    await rename(join(directory, "codex/agents/sample-reviewer.toml"), join(directory, "codex/agents/obsolete.toml"));
    await writeFile(join(directory, "codex/agents/second-reviewer.toml"), "Edited output.\n");
    await writeFile(join(directory, "codex/agents/unowned.toml"), "# User-owned configuration.\n");

    const changed = [
      "agents/first.md", "agents/renamed.md", "agents/second.md",
      "codex/agents/obsolete.toml", "codex/agents/sample-reviewer.toml", "codex/agents/second-reviewer.toml",
    ];
    expect(await generateAgents(directory, true)).toEqual(changed);
    expect(await readFile(join(directory, "agents/first.md"), "utf8")).toBe(previous);
    expect(await readFile(join(directory, "agents/second.md"), "utf8")).toBe("Edited output.\n");
    expect(await readFile(join(directory, "codex/agents/second-reviewer.toml"), "utf8")).toBe("Edited output.\n");
    await expect(readFile(join(directory, "agents/renamed.md"))).rejects.toMatchObject({ code: "ENOENT" });
    await expect(readFile(join(directory, "codex/agents/sample-reviewer.toml"))).rejects.toMatchObject({ code: "ENOENT" });
    expect(await readFile(join(directory, "codex/agents/obsolete.toml"), "utf8")).toContain("# Generated");

    expect(await generateAgents(directory)).toEqual(changed);
    await expect(readFile(join(directory, "agents/first.md"))).rejects.toMatchObject({ code: "ENOENT" });
    await expect(readFile(join(directory, "codex/agents/obsolete.toml"))).rejects.toMatchObject({ code: "ENOENT" });
    expect(await readFile(join(directory, "agents/renamed.md"), "utf8")).toBe(previous);
    expect(await readFile(join(directory, "agents/handwritten.md"), "utf8")).toBe(handwritten);
    expect(await readFile(join(directory, "codex/agents/unowned.toml"), "utf8")).toBe("# User-owned configuration.\n");
    expect(await generateAgents(directory, true)).toEqual([]);
  });

  test("updates, renames, and removes Codex outputs with their canonical roles", async () => {
    await generateAgents(directory);
    await writeFile(join(directory, "agents/handwritten.md"), handwritten.replace("Handwritten instructions.", "Changed instructions."));
    expect(await generateAgents(directory)).toEqual(["codex/agents/handwritten.toml"]);
    const config = parseToml(await readFile(join(directory, "codex/agents/handwritten.toml"), "utf8"));
    expect(config.developer_instructions).toBe("Changed instructions.");

    await writeFile(join(directory, "agents/handwritten.md"), handwritten.replace("name: handwritten", "name: renamed"));
    expect(await generateAgents(directory)).toEqual(["codex/agents/handwritten.toml", "codex/agents/renamed.toml"]);
    await rm(join(directory, "agents/handwritten.md"));
    await rm(join(directory, "templates/reviewers/roles/first.md"));
    const removed = ["agents/first.md", "codex/agents/renamed.toml", "codex/agents/sample-reviewer.toml"];
    expect(await generateAgents(directory, true)).toEqual(removed);
    expect(await generateAgents(directory)).toEqual(removed);
    expect(await generateAgents(directory, true)).toEqual([]);
  });

  test.each([
    [handwritten.replace("name: handwritten", "name: sample-reviewer"), "Duplicate agent name"],
    [handwritten.replace("name: handwritten", "name: ../escape"), "kebab-case"],
  ])("invalid source identity fails before either format is written", async (invalid, error) => {
    await writeFile(join(directory, "agents/handwritten.md"), invalid);
    await expect(generateAgents(directory)).rejects.toThrow(error);
    await expect(readFile(join(directory, "agents/first.md"))).rejects.toMatchObject({ code: "ENOENT" });
    await expect(readFile(join(directory, "codex/agents"))).rejects.toMatchObject({ code: "ENOENT" });
    expect(await readFile(join(directory, "agents/handwritten.md"), "utf8")).toBe(invalid);
  });

  test("CLI resolves its repository independently of cwd and returns a failing status for drift", async () => {
    const script = join(directory, "scripts/generate-agents.ts");
    await copyFile(join(root, "scripts/generate-agents.ts"), script);
    await symlink(join(root, "node_modules"), join(directory, "node_modules"), "junction");
    // The real package is ESM, including when run through native Node TypeScript support.
    await writeFile(join(directory, "package.json"), '{"type":"module"}\n');
    await expect(exec(process.execPath, [script, "--check"], { cwd: tmpdir() })).rejects.toMatchObject({
      code: 1,
      stderr: expect.stringContaining("codex/agents/sample-reviewer.toml"),
    });
    await expect(readFile(join(directory, "agents/first.md"))).rejects.toMatchObject({ code: "ENOENT" });
    await exec(process.execPath, [script], { cwd: tmpdir() });
    await expect(exec(process.execPath, [script, "--check"], { cwd: tmpdir() })).resolves.toMatchObject({ stderr: "" });
  });
});
