import { execFile } from "node:child_process";
import { copyFile, mkdir, mkdtemp, readFile, rename, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";
import { afterEach, beforeEach, describe, expect, test } from "vitest";
import { generateAgents, renderReviewer } from "../scripts/generate-agents.ts";

const exec = promisify(execFile);
const root = resolve(import.meta.dirname, "..");
const template = "{{introduction}}\n\nShared boundary.\n\n{{review}}\n\n{{focus}}\n\n{{report}}\n";
const role = "---\nname: sample-reviewer\ndescription: Sample role\n---\n\n# Sample\n\nIntroduction.\n\n## Focus\n\nSpecific focus.\n";
const reviewing = "# Reviewing\n\n## Selection\n\nParent-only selection.\n\n## Review\n\nShared review.\n\n## Report\n\nShared report.\n\n## Other\n\nUnrelated section.\n";

describe("reviewer composition", () => {
  test("preserves frontmatter and specialist content while including only the selected shared sections", () => {
    const result = renderReviewer(template, role, reviewing);
    expect(result).toMatch(/^---\nname: sample-reviewer\ndescription: Sample role\n---\n/);
    expect(result).toContain("<!-- Generated by scripts/generate-agents.ts.");
    expect(result).toContain("# Sample\n\nIntroduction.");
    expect(result).toContain("Shared boundary.\n\n## Review\n\nShared review.\n\n## Focus\n\nSpecific focus.\n\n## Report\n\nShared report.\n");
    expect(result).not.toContain("Parent-only selection.");
    expect(result).not.toContain("Unrelated section.");
    expect(result).not.toContain("{{");
    expect(renderReviewer(template, role, reviewing)).toBe(result);
    const crlf = (text: string) => text.replaceAll("\n", "\r\n");
    expect(renderReviewer(crlf(template), crlf(role), crlf(reviewing))).toBe(result);
  });

  test.each([
    template.replace("{{review}}", ""),
    template.replace("{{review}}", "{{unknown}}"),
    template + "{{report}}",
  ])("rejects missing, unknown, or duplicate composition slots", (invalid) => {
    expect(() => renderReviewer(invalid, role, reviewing)).toThrow("slot");
  });

  test("reports missing source sections rather than silently omitting them", () => {
    expect(() => renderReviewer(template, role.replace("## Focus", "## Other"), reviewing)).toThrow("## Focus");
    expect(() => renderReviewer(template, role, reviewing.replace("## Report", "## Other report"))).toThrow("## Report");
  });

  test("committed reviewers match their authoritative sources", async () => {
    expect(await generateAgents(root, true)).toEqual([]);
  });
});

describe("generation and drift checking", () => {
  let directory: string;

  beforeEach(async () => {
    directory = await mkdtemp(join(tmpdir(), "agentic-skills-generation-"));
    for (const path of ["templates/reviewers/roles", "skills/agentic-reviewing", "agents", "scripts"]) {
      await mkdir(join(directory, path), { recursive: true });
    }
    await writeFile(join(directory, "templates/reviewers/template.md"), template);
    await writeFile(join(directory, "templates/reviewers/roles/first.md"), role);
    await writeFile(join(directory, "templates/reviewers/roles/second.md"), role.replace("sample-reviewer", "second-reviewer"));
    await writeFile(join(directory, "skills/agentic-reviewing/SKILL.md"), reviewing);
    await writeFile(join(directory, "agents/handwritten.md"), "Handwritten role.\n");
  });

  afterEach(async () => {
    await rm(directory, { recursive: true, force: true });
  });

  test("generates self-contained outputs and propagates a shared source change to every reviewer", async () => {
    expect(await generateAgents(directory)).toEqual(["agents/first.md", "agents/second.md"]);
    expect(await generateAgents(directory)).toEqual([]);
    expect(await generateAgents(directory, true)).toEqual([]);

    await writeFile(join(directory, "skills/agentic-reviewing/SKILL.md"), reviewing.replace("Shared review.", "Updated method."));
    expect(await generateAgents(directory)).toEqual(["agents/first.md", "agents/second.md"]);
    for (const name of ["first", "second"]) {
      const content = await readFile(join(directory, `agents/${name}.md`), "utf8");
      expect(content).toContain("Updated method.");
      expect(content).toContain("Specific focus.");
      expect(content).toContain("Shared report.");
    }
    expect(await readFile(join(directory, "agents/handwritten.md"), "utf8")).toBe("Handwritten role.\n");
  });

  test("check detects missing, changed, and obsolete outputs without mutation; generation reconciles only owned files", async () => {
    await generateAgents(directory);
    const previous = await readFile(join(directory, "agents/first.md"), "utf8");
    await rename(join(directory, "templates/reviewers/roles/first.md"), join(directory, "templates/reviewers/roles/renamed.md"));
    await writeFile(join(directory, "agents/second.md"), "Edited output.\n");

    const changed = ["agents/first.md", "agents/renamed.md", "agents/second.md"];
    expect(await generateAgents(directory, true)).toEqual(changed);
    expect(await readFile(join(directory, "agents/first.md"), "utf8")).toBe(previous);
    expect(await readFile(join(directory, "agents/second.md"), "utf8")).toBe("Edited output.\n");
    await expect(readFile(join(directory, "agents/renamed.md"))).rejects.toMatchObject({ code: "ENOENT" });

    expect(await generateAgents(directory)).toEqual(changed);
    await expect(readFile(join(directory, "agents/first.md"))).rejects.toMatchObject({ code: "ENOENT" });
    expect(await readFile(join(directory, "agents/renamed.md"), "utf8")).toBe(previous);
    expect(await readFile(join(directory, "agents/handwritten.md"), "utf8")).toBe("Handwritten role.\n");
    expect(await generateAgents(directory, true)).toEqual([]);
  });

  test("CLI resolves its repository independently of cwd and returns a failing status for drift", async () => {
    const script = join(directory, "scripts/generate-agents.ts");
    await copyFile(join(root, "scripts/generate-agents.ts"), script);
    // The real package is ESM, including when run through native Node TypeScript support.
    await writeFile(join(directory, "package.json"), '{"type":"module"}\n');
    await expect(exec(process.execPath, [script, "--check"], { cwd: tmpdir() })).rejects.toMatchObject({
      code: 1,
      stderr: expect.stringContaining("agents/first.md"),
    });
    await expect(readFile(join(directory, "agents/first.md"))).rejects.toMatchObject({ code: "ENOENT" });
    await exec(process.execPath, [script], { cwd: tmpdir() });
    await expect(exec(process.execPath, [script, "--check"], { cwd: tmpdir() })).resolves.toMatchObject({ stderr: "" });
  });
});
