import { readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const generatedNotice = "<!-- Generated by scripts/generate-agents.ts. Edit templates/reviewers/ or skills/agentic-reviewing/SKILL.md, then run npm run generate. -->";

function section(markdown: string, heading: string): string {
  const result = markdown.split(/(?=^## )/m).find((part) => part.startsWith(`## ${heading}\n`));
  if (!result) throw new Error(`Reviewing skill is missing the "## ${heading}" section.`);
  return result.trimEnd();
}

export function renderReviewer(template: string, role: string, reviewing: string): string {
  [template, role, reviewing] = [template, role, reviewing].map((text) => text.replaceAll("\r\n", "\n"));
  const parts = role.split(/(?=^## )/m);
  if (parts.length !== 2 || !parts[1].startsWith("## Focus\n")) {
    throw new Error('Role source must contain an introduction followed by one "## Focus" section.');
  }
  const frontmatter = /^(---\n[\s\S]*?\n---\n)/;
  if (!frontmatter.test(parts[0])) throw new Error("Role source must start with YAML frontmatter.");

  const slots: Record<string, string> = {
    introduction: parts[0].trimEnd(),
    review: section(reviewing, "Review"),
    focus: parts[1].trimEnd(),
    report: section(reviewing, "Report"),
  };
  const tokens = [...template.matchAll(/\{\{([^{}]+)\}\}/g)].map((match) => match[1]);
  if (JSON.stringify(tokens.sort()) !== JSON.stringify(Object.keys(slots).sort())) {
    throw new Error("Reviewer template must contain exactly one of each slot: introduction, review, focus, report.");
  }
  const rendered = template.replace(/\{\{([^{}]+)\}\}/g, (_, key: string) => slots[key]);
  return rendered.replace(frontmatter, `$1\n${generatedNotice}\n`).trimEnd() + "\n";
}

async function readOutput(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

/** Return changed output paths; check mode never writes or removes files. */
export async function generateAgents(root: string, check = false): Promise<string[]> {
  const sourceDir = join(root, "templates/reviewers");
  const roleDir = join(sourceDir, "roles");
  const outputDir = join(root, "agents");
  const template = await readFile(join(sourceDir, "template.md"), "utf8");
  const reviewing = await readFile(join(root, "skills/agentic-reviewing/SKILL.md"), "utf8");
  const roles = (await readdir(roleDir)).filter((name) => name.endsWith(".md")).sort();
  const outputs = new Map<string, string>();
  for (const name of roles) {
    const sourcePath = join(roleDir, name);
    const role = await readFile(sourcePath, "utf8");
    try {
      outputs.set(name, renderReviewer(template, role, reviewing));
    } catch (error) {
      throw new Error(`${sourcePath}: ${(error as Error).message}`, { cause: error });
    }
  }

  const names = new Set([...roles, ...(await readdir(outputDir)).filter((name) => name.endsWith(".md"))]);
  const changed: string[] = [];
  for (const name of [...names].sort()) {
    const path = join(outputDir, name);
    const current = await readOutput(path);
    const expected = outputs.get(name);
    // Only generated files are removed when their role source is deleted.
    if (expected === undefined && !current?.includes(generatedNotice)) continue;
    if (current === expected) continue;
    changed.push(`agents/${name}`);
    if (!check) {
      if (expected === undefined) await rm(path);
      else await writeFile(path, expected);
    }
  }
  return changed;
}

if (import.meta.main) {
  try {
    const args = process.argv.slice(2);
    if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
      throw new Error("Usage: node scripts/generate-agents.ts [--check]");
    }
    const check = args[0] === "--check";
    const changed = await generateAgents(fileURLToPath(new URL("..", import.meta.url)), check);
    if (check && changed.length) {
      console.error(`Generated agents are out of date:\n${changed.join("\n")}\nRun npm run generate.`);
      process.exitCode = 1;
    } else {
      console.log(changed.length ? `Updated:\n${changed.join("\n")}` : "Generated agents are up to date.");
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}
