import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { stringify } from "smol-toml";
import { parse } from "yaml";

const generatedNotice = "<!-- Generated by scripts/generate-agents.ts. Edit templates/reviewers/ or skills/agentic-reviewing/SKILL.md, then run npm run generate. -->";

const codexNotice = "# Generated by scripts/generate-agents.ts. Edit the owning Markdown sources, then run npm run generate.";

function section(markdown: string, heading: string): string {
  const result = markdown.split(/(?=^## )/m).find((part) => part.startsWith(`## ${heading}\n`));
  if (!result) throw new Error(`Reviewing skill is missing the "## ${heading}" section.`);
  return result.trimEnd();
}

export function renderReviewer(template: string, role: string, reviewing: string): string {
  [template, role, reviewing] = [template, role, reviewing].map((text) => text.replaceAll("\r\n", "\n"));
  const parts = role.split(/(?=^## )/m);
  if (parts.length !== 2 || !parts[1].startsWith("## Focus\n")) {
    throw new Error('Role source must contain an introduction followed by one "## Focus" section.');
  }
  const frontmatter = /^(---\n[\s\S]*?\n---\n)/;
  if (!frontmatter.test(parts[0])) throw new Error("Role source must start with YAML frontmatter.");

  const slots: Record<string, string> = {
    introduction: parts[0].trimEnd(),
    review: section(reviewing, "Review"),
    focus: parts[1].trimEnd(),
    report: section(reviewing, "Report"),
  };
  const tokens = [...template.matchAll(/\{\{([^{}]+)\}\}/g)].map((match) => match[1]);
  if (JSON.stringify(tokens.sort()) !== JSON.stringify(Object.keys(slots).sort())) {
    throw new Error("Reviewer template must contain exactly one of each slot: introduction, review, focus, report.");
  }
  const rendered = template.replace(/\{\{([^{}]+)\}\}/g, (_, key: string) => slots[key]);
  return rendered.replace(frontmatter, `$1\n${generatedNotice}\n`).trimEnd() + "\n";
}

export function renderCodexAgent(markdown: string): { name: string; content: string } {
  const match = markdown.replaceAll("\r\n", "\n").match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("Agent must start with YAML frontmatter.");
  const metadata = parse(match[1]);
  if (!metadata || typeof metadata.name !== "string" || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(metadata.name)) {
    throw new Error("Agent name must be a nonempty kebab-case identifier.");
  }
  if (typeof metadata.description !== "string" || !metadata.description.trim()) {
    throw new Error("Agent description must be a nonempty string.");
  }
  const instructions = match[2].replace(generatedNotice, "").trim();
  if (!instructions) throw new Error("Agent instructions must not be empty.");
  return {
    name: metadata.name,
    content: codexNotice + "\n" + stringify({
      name: metadata.name,
      description: metadata.description,
      developer_instructions: instructions,
    }),
  };
}

async function readDirectory(path: string): Promise<string[]> {
  try {
    return await readdir(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }
}

async function readOutput(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

/** Return changed output paths; check mode never writes or removes files. */
export async function generateAgents(root: string, check = false): Promise<string[]> {
  const sourceDir = join(root, "templates/reviewers");
  const roleDir = join(sourceDir, "roles");
  const template = await readFile(join(sourceDir, "template.md"), "utf8");
  const reviewing = await readFile(join(root, "skills/agentic-reviewing/SKILL.md"), "utf8");
  const roles = (await readdir(roleDir)).filter((name) => name.endsWith(".md")).sort();
  const outputs = new Map<string, string>();
  for (const name of roles) {
    const sourcePath = join(roleDir, name);
    const role = await readFile(sourcePath, "utf8");
    try {
      outputs.set(`agents/${name}`, renderReviewer(template, role, reviewing));
    } catch (error) {
      throw new Error(`${sourcePath}: ${(error as Error).message}`, { cause: error });
    }
  }

  const markdownFiles = (await readDirectory(join(root, "agents"))).filter((name) => name.endsWith(".md"));
  const codexFiles = (await readDirectory(join(root, "codex/agents"))).filter((name) => name.endsWith(".toml"));
  const agents = new Map(outputs);
  for (const name of markdownFiles.sort()) {
    const path = `agents/${name}`;
    // Current reviewer paths belong to their templates, even if someone removed the notice.
    if (agents.has(path)) continue;
    const markdown = await readFile(join(root, path), "utf8");
    if (!markdown.includes(generatedNotice)) agents.set(path, markdown);
  }
  for (const [sourcePath, markdown] of agents) {
    try {
      const { name, content } = renderCodexAgent(markdown);
      const path = `codex/agents/${name}.toml`;
      if (outputs.has(path)) throw new Error(`Duplicate agent name: ${name}`);
      outputs.set(path, content);
    } catch (error) {
      throw new Error(`${join(root, sourcePath)}: ${(error as Error).message}`, { cause: error });
    }
  }

  // Render and validate every source before changing either output format.
  const paths = new Set([
    ...outputs.keys(),
    ...markdownFiles.map((name) => `agents/${name}`),
    ...codexFiles.map((name) => `codex/agents/${name}`),
  ]);
  const changed: string[] = [];
  for (const relativePath of [...paths].sort()) {
    const path = join(root, relativePath);
    const current = await readOutput(path);
    const expected = outputs.get(relativePath);
    const notice = relativePath.endsWith(".toml") ? codexNotice : generatedNotice;
    // Only marked generated files are removed when their source is deleted.
    if (expected === undefined && !current?.includes(notice)) continue;
    if (current === expected) continue;
    changed.push(relativePath);
    if (!check) {
      if (expected === undefined) await rm(path);
      else {
        await mkdir(dirname(path), { recursive: true });
        await writeFile(path, expected);
      }
    }
  }
  return changed;
}

if (import.meta.main) {
  try {
    const args = process.argv.slice(2);
    if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
      throw new Error("Usage: node scripts/generate-agents.ts [--check]");
    }
    const check = args[0] === "--check";
    const changed = await generateAgents(fileURLToPath(new URL("..", import.meta.url)), check);
    if (check && changed.length) {
      console.error(`Generated agents are out of date:\n${changed.join("\n")}\nRun npm run generate.`);
      process.exitCode = 1;
    } else {
      console.log(changed.length ? `Updated:\n${changed.join("\n")}` : "Generated agents are up to date.");
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}
